defaults:
  - _self_
  - task@_global_: quadruped_walk
  - override hydra/launcher: submitit_local

# task settings
frame_stack: 1
action_repeat: 1
discount: 0.99
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 100000
replay_buffer_num_workers: 1
nstep: 1
batch_size: 256
# misc
seed: 1
device: cuda
save_video: true
save_train_video: true
use_tb: true
# experiment
# experiment: metaworld_reach_lowdim_standardreward
experiment: metaworld_reach_lowdim_customreward
# experiment: metaworld_reach_img_standardreward
# experiment: metaworld_reach_img_customreward
# agent
lr: 1e-4
feature_dim: 50

# dxy
use_image_state_space: False
use_custom_reward: True


agent:
  _target_: drqv2.DrQV2Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_sweep_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 48
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
